---
- name: Install PostgreSQL on Target VM
  hosts: your_target_vm
  become: yes

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL and PostgreSQL-contrib packages
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present

    - name: Ensure PostgreSQL service is started and enabled
      systemd:
        name: postgresql
        state: started
        enabled: yes
